version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@postgres:5432/realtime_notes
      - PORT=3000
      - SESSION_SECRET=your-secret-key-here
    restart: unless-stopped
    volumes:
      - ./server:/app/server
      - ./client/dist:/app/client/dist
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=realtime_notes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
